### ISSUE TITLE
NoMethodError: undefined method `trigger'

### ISSUE THREAD

**Issue by thinhluu** [logstash-plugins/logstash-output-cloudwatch#6]
Looks like there is a bug when @event_queue.length >= @event_queue.max. It is calling a trigger() of a string instead of an object. Here is the bebug info: 

output received {:event=>{"message"=>"2014-12-03 10:27:07 INFO: InsertedAt=2014-12-03 18:26:53; EventID=1060506; EventTime=2014-12-03 18:26:52; EventTypeID=9; EventType=Web; Name=cat:-1; ReportingName=cat:-1; UserName=XXX\xyzuser; ActionID=1; Action=Blocked; SubTypeID=2; SubType=Web control; RuleID=; BlockedSite=google-cm.p.veruta.com/adserver/cookiematch; ReferringURL=cm.g.doubleclick.net/push; ComputerName=POME-MANAGER83; ComputerDomain=XXX; ComputerIPAddress=169.254.217.98", "@version"=>"1", "@timestamp"=>"2015-10-29T15:42:50.122Z", "CW_metricname"=>"InfosecEvents", "file"=>"C:\Program Files (x86)\Sophos\Reporting Interface\Log Files\Web.log", "host"=>"WIN-XXX", "offset"=>"2344085", "type"=>"syslog"}, :level=>:debug, :file=>"(eval)", :line=>"29", :method=>"output_func"}
inputs/LogStash::Inputs::Lumberjack: adding value to field {:field=>"CW_metricname", :value=>["InfosecEvents"], :level=>:debug, :file=>"logstash/util/decorators.rb", :line=>"27", :method=>"add_fields"}
NoMethodError: undefined method `trigger' for "every_1446133310.734_0":String
        receive at /opt/logstash/vendor/local_gems/1af70037/logstash-output-cloudwatch-2.0.2/lib/logstash/outputs/cloudwatch.rb:191
        handle at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.4-java/lib/logstash/outputs/base.rb:88
    output_func at (eval):31
  outputworker at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.4-java/lib/logstash/pipeline.rb:244
  start_outputs at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.4-java/lib/logstash/pipeline.rb:166
Lumberjack input: unhandled exception {:exception=>#<ConcurrencyError: No message available>, :backtrace=>["org/jruby/ext/thread/ConditionVariable.java:98:in`wait'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-lumberjack-1.0.6/lib/logstash/sized_queue_timeout.rb:30:in `push'", "org/jruby/ext/thread/Mutex.java:149:in`synchronize'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-lumberjack-1.0.6/lib/logstash/sized_queue_timeout.rb:27:in `push'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-lumberjack-1.0.6/lib/logstash/inputs/lumberjack.rb:81:in`run'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-lumberjack-1.0.6/lib/logstash/circuit_breaker.rb:42:in `execute'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-lumberjack-1.0.6/lib/logstash/inputs/lumberjack.rb:81:in`run'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-codec-plain-1.0.0/lib/logstash/codecs/plain.rb:35:in `decode'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-lumberjack-1.0.6/lib/logstash/inputs/lumberjack.rb:77:in`run'", "org/jruby/RubyProc.java:271:in `call'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-lumberjack-1.0.6/lib/logstash/inputs/lumberjack.rb:105:in`invoke'", "org/jruby/RubyProc.java:271:in `call'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/jls-lumberjack-0.0.26/lib/lumberjack/server.rb:372:in`data'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/jls-lumberjack-0.0.26/lib/lumberjack/server.rb:340:in `read_socket'", "org/jruby/RubyProc.java:271:in`call'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/jls-lumberjack-0.0.26/lib/lumberjack/server.rb:363:in `ack_if_needed'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/jls-lumberjack-0.0.26/lib/lumberjack/server.rb:340:in`read_socket'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/jls-lumberjack-0.0.26/lib/lumberjack/server.rb:280:in `data_field_value'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/jls-lumberjack-0.0.26/lib/lumberjack/server.rb:163:in`feed'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/jls-lumberjack-0.0.26/lib/lumberjack/server.rb:296:in `compressed_payload'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/jls-lumberjack-0.0.26/lib/lumberjack/server.rb:163:in`feed'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/jls-lumberjack-0.0.26/lib/lumberjack/server.rb:332:in `read_socket'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/jls-lumberjack-0.0.26/lib/lumberjack/server.rb:315:in`run'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-lumberjack-1.0.6/lib/logstash/inputs/lumberjack.rb:104:in `invoke'", "org/jruby/RubyProc.java:271:in`call'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/concurrent-ruby-0.9.1-java/lib/concurrent/executor/executor_service.rb:515:in `run'", "Concurrent$$JavaExecutorService$$Job_1733550788.gen:13:in`run'"], :level=>:error, :file=>"logstash/inputs/lumberjack.rb", :line=>"117", :method=>"invoke"}

**Comment by davidstelter** [comment]
I'm seeing this too, logstash-output-cloudwatch-2.0.4/lib/logstash/outputs/cloudwatch.rb:191 running on Amazon Linux, logstash RPM version logstash-2.3.2-1.noarch from the elastic.co yum repo. This bug crashes the whole logstash shipper and renders this plugin unusable!

**Comment by jkotrlik** [comment]
Got that too, Ubuntu 14.04.4 aws machine
NoMethodError: undefined method `trigger' for "every_1465999151.04_0":String
               receive at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-cloudwatch-2.0.4/lib/logstash/outputs/cloudwatch.rb:191
         multi_receive at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.2-java/lib/logstash/outputs/base.rb:83
                  each at org/jruby/RubyArray.java:1613
         multi_receive at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.2-java/lib/logstash/outputs/base.rb:83
  worker_multi_receive at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.2-java/lib/logstash/output_delegator.rb:130
  worker_multi_receive at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.2-java/lib/logstash/output_delegator.rb:129
         multi_receive at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.2-java/lib/logstash/output_delegator.rb:114
          output_batch at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.2-java/lib/logstash/pipeline.rb:301
                  each at org/jruby/RubyHash.java:1342
          output_batch at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.2-java/lib/logstash/pipeline.rb:301
           worker_loop at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.2-java/lib/logstash/pipeline.rb:232
         start_workers at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.2-java/lib/logstash/pipeline.rb:201

**Comment by thinhluu** [comment]
- Setting the queue size to a big number is a quick workaround (queue_size => 1000000000)
- Or fix the problem in the code:
  if (@event_queue.length >= @event_queue.max)
    #@job.trigger
    publish(aggregate({}))
    @logger.warn("Posted to AWS CloudWatch ahead of schedule.  If you see this often, consider increasing the cloudwatch queue_size option.")
  end

**Comment by jtopper** [comment]
We're hitting this today too.

Is it notable that in these lines https://github.com/logstash-plugins/logstash-output-cloudwatch/blob/master/lib/logstash/outputs/cloudwatch.rb#L177-L189 there are calls to `@job.trigger` and `job.trigger`. The `@job.trigger` call is on the failing line.

**Comment by warrenjmcdonald** [comment]
This is still current and easily reproducible with a reasonable metric volume. It is fairly crucial too, as one of the main reasons to send to Cloudwatch is for alarms on metrics.

Current situation is that if you receive more records to aggregate than you expected with the queue_size you have set, you will get nothing in Cloudwatch as the fatal error clears the counter. 

I spent half an hour looking at Cloudwatch metrics graphs at 0 with ES counters for the same CW_metricname field value going through the roof, as the ES output survives the crash, but the aggregated stats in CW output don't.

**Comment by Mexx77** [comment]
I still have the issue...

**Comment by DoNotMicrowave** [comment]
This seems like something that should get some attention soon. Was crashing my production Logstash earlier. Now I suppose I need to best-guess what queue_size should be, figure out if it will affect memory consumption (even if it's not filling), and hope that the queue size never gets high enough during timeframe to crash (yuck). Also there are known bugs with the statsd plugin that have not been fixed. Moved to CloudWatch to escape the big one (TCP mode busted out of the gate) that was affecting me there! :man_shrugging:
